version: '3'
services:
  backend:
    restart: on-failure
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
      - rabbitmq
  db:
    image: postgres
    restart: on-failure
    container_name: postgresdb    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commerce_db
    ports:
      - '5432:5432'     
  redis:
    image: redis
    restart: on-failure
    container_name: redis    
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    container_name: rabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    ports:
      - "5672:5672"
      - "15672:15672"
